server:
  port: 8189
  servlet:
    context-path: /market-core
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/core
    hikari:
      username: postgres
      password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: my_market