server:
  port: 8188
  servlet:
    context-path: /market-order
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/order
    hikari:
      username: postgres
      password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
integrations:
  cart-service:
    url: http://localhost:5555/cart
    connect-timeout: 2000
    read-timeout: 10000
    write-timeout: 2000
