server:
  port: 5555

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/market-realm
        registration:
          core-client:
            provider: keycloak
            client-id: market-client
            client-secret: e4Tft6a9okn4nECCe34H8LL1KN7IxXFn
            scope:
              - read
              - write
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
        - TokenRelay=
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8189/
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-core
        - id: cart-service
          uri: http://localhost:8187/
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-cart
        - id: auth-service
          uri: http://localhost:8186/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-auth
        - id: order-service
          uri: http://localhost:8188/
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-order
        - id: keycloak
          uri: http://localhost:8090/
          predicates:
            - Path=/realms/**

